const FLAVORS = {
  jodii: {
    appType: 115,
    appName: 'BharatJodii',
    applicationId: 'jodii.app',
    scheme: 'jodii',
    domain: 'jodii.app',
    // BharatJodii rebrand: old SMS links / OneLink shares already in
    // circulation still point at jodii.app, so the new host is added
    // alongside it (additive, matching the native Android app's own
    // dual-host App Link migration) rather than replacing `domain` outright.
    // Only the root flavor gets a second host — every other flavor is
    // untouched by this rebrand's domain change.
    domain2: 'bharatjodii.com',
    welcomeText: 'Welcome to BharatJodii',
    icon: './assets/icon.png',
    // Android adaptive icons mask/zoom the foreground layer down to a ~66%
    // safe zone (this is what Android itself uses when auto-wrapping legacy
    // icons, and what the old native app's icon effectively respected via
    // its own generous text padding — see app_logo.xml). `icon` above fills
    // the full 1024x1024 canvas edge-to-edge (fine for iOS/splash/store
    // listing), so feeding it straight to adaptiveIcon.foregroundImage let
    // the "Bharat Jodii" text get clipped by the mask on real devices. This
    // is the same artwork pre-scaled to 66% on a matching maroon background
    // so nothing gets cropped.
    adaptiveIcon: './assets/icons/bharatjodii-adaptive-icon.png',
    // Sampled from assets/icon.png's own corner pixel — matches the maroon
    // card the logo is drawn on, instead of the old unrelated light-blue
    // default (plugins/withAndroidFlavors.js and app.config.js both fall
    // back to that old default for every other flavor, unchanged).
    adaptiveIconBackground: '#ffffff',
    // BharatJodii rebrand: notification small-icon, ported from the native
    // Android app's per-flavor drawable/ic_notify_logo.png (see app.config.js's
    // expo-notifications plugin config). Only this flavor + the 8 below got a
    // redesigned one in the reference migration — every other flavor falls
    // back to its own `icon` above.
    notifyIcon: './assets/icons/bharatjodii-logo.png',
    playStoreUrl: 'https://play.google.com/store/apps/details?id=jodii.app&hl=en_US&gl=US',
  },
  tamil: {
    appType: 116,
    appName: 'TamilJodii',
    applicationId: 'jodiiapp.android.tamil',
    scheme: 'tamilmatrimony',
    domain: 'tamil.jodii.app',
    welcomeText: 'Welcome to Tamil Jodii',
    icon: './assets/icons/logos/tamil_jodii.png',
    notifyIcon: './assets/icons/tamil-logo.png',
    playStoreUrl: 'https://play.google.com/store/apps/details?id=jodiiapp.android.tamil',
  },
  malayalam: {
    appType: 118,
    appName: 'MalayalamJodii',
    applicationId: 'jodiiapp.android.malayalam',
    scheme: 'malayalammatrimony',
    domain: 'malayalam.jodii.app',
    welcomeText: 'Welcome to Malayalam Jodii',
    icon: './assets/icons/logos/malayalam_jodii.png',
    notifyIcon: './assets/icons/malayalam-logo.png',
    playStoreUrl: 'https://play.google.com/store/apps/details?id=jodiiapp.android.malayalam',
  },
  // Remaining flavors ported from the old native Android project's
  // build.gradle.kts.jinja (productFlavors, dimension "app"). Keys use this
  // project's shortened-name convention (matching jodii/tamil/malayalam
  // above) rather than the native project's raw flavor names (e.g.
  // "brahminjodii") — applicationId/appType are copied verbatim from there.
  // icon left as the generic Jodii icon as a placeholder — real per-flavor
  // icons to be swapped in later.
  telugu: {
    appType: 117,
    appName: 'TeluguJodii',
    applicationId: 'jodiiapp.android.telugu',
    scheme: 'telugujodii',
    domain: 'telugu.jodii.app',
    welcomeText: 'Welcome to Telugu Jodii',
    icon: './assets/icons/logos/telugu_jodii.png',
    notifyIcon: './assets/icons/telugu-logo.png',
    playStoreUrl: 'https://play.google.com/store/apps/details?id=jodiiapp.android.telugu',
  },
  kannada: {
    appType: 119,
    appName: 'KannadaJodii',
    applicationId: 'jodiiapp.android.kannada',
    scheme: 'kannadajodii',
    domain: 'kannada.jodii.app',
    welcomeText: 'Welcome to Kannada Jodii',
    icon: './assets/icons/logos/kannada_jodii.png',
    notifyIcon: './assets/icons/kannada-logo.png',
    playStoreUrl: 'https://play.google.com/store/apps/details?id=jodiiapp.android.kannada',
  },
  oriya: {
    appType: 120,
    appName: 'OriyaJodii',
    applicationId: 'jodiiapp.android.oriya',
    scheme: 'oriyajodii',
    domain: 'oriya.jodii.app',
    welcomeText: 'Welcome to Oriya Jodii',
    icon: './assets/icons/logos/oriya_jodii.png',
    notifyIcon: './assets/icons/oriya-logo.png',
    playStoreUrl: 'https://play.google.com/store/apps/details?id=jodiiapp.android.oriya',
  },
  bengali: {
    appType: 121,
    appName: 'BengaliJodii',
    applicationId: 'jodiiapp.android.bengali',
    scheme: 'bengalijodii',
    domain: 'bengali.jodii.app',
    welcomeText: 'Welcome to Bengali Jodii',
    icon: './assets/icons/logos/bengali_jodii.png',
    notifyIcon: './assets/icons/bengali-logo.png',
    playStoreUrl: 'https://play.google.com/store/apps/details?id=jodiiapp.android.bengali',
  },
  marathi: {
    appType: 122,
    appName: 'MarathiJodii',
    applicationId: 'jodiiapp.android.marathi',
    scheme: 'marathijodii',
    domain: 'marathi.jodii.app',
    welcomeText: 'Welcome to Marathi Jodii',
    icon: './assets/icons/logos/marathi_jodii.png',
    notifyIcon: './assets/icons/marathi-logo.png',
    playStoreUrl: 'https://play.google.com/store/apps/details?id=jodiiapp.android.marathi',
  },
  gujarati: {
    appType: 123,
    appName: 'GujaratiJodii',
    applicationId: 'jodiiapp.android.gujarati',
    scheme: 'gujarathijodii',
    domain: 'gujarati.jodii.app',
    welcomeText: 'Welcome to Gujarati Jodii',
    icon: './assets/icons/logos/gujarati_jodii.png',
    notifyIcon: './assets/icons/gujarati-logo.png',
    playStoreUrl: 'https://play.google.com/store/apps/details?id=jodiiapp.android.gujarati',
  },
  hindi: {
    appType: 124,
    appName: 'HindiJodii',
    applicationId: 'jodiiapp.android.hindi',
    scheme: 'hindijodii',
    domain: 'hindi.jodii.app',
    welcomeText: 'Welcome to Hindi Jodii',
    icon: './assets/icons/logos/hindi_jodii.png',
    playStoreUrl: 'https://play.google.com/store/apps/details?id=jodiiapp.android.hindi',
  },
  punjabi: {
    appType: 125,
    appName: 'PunjabiJodii',
    applicationId: 'jodiiapp.android.punjabi',
    scheme: 'punjabijodii',
    domain: 'punjabi.jodii.app',
    welcomeText: 'Welcome to Punjabi Jodii',
    icon: './assets/icons/logos/punjabi_jodii.png',
    notifyIcon: './assets/icons/punjabi-logo.png',
    playStoreUrl: 'https://play.google.com/store/apps/details?id=jodiiapp.android.punjabi',
  },
  ninetysixkulimaratha: {
    appType: 301,
    appName: 'NinetysixkulimarathaJodii',
    applicationId: 'ninetysixkulimaratha.jodii.com',
    scheme: 'ninetysixkulimaratha',
    domain: 'ninetysixkulimaratha.jodii.com',
    welcomeText: 'Welcome to Ninetysixkulimaratha Jodii',
    icon: './assets/icons/logos/ninetysixkulimaratha_jodii.png',
    playStoreUrl: 'https://play.google.com/store/apps/details?id=ninetysixkulimaratha.jodii.com',
  },
  ezhava: {
    appType: 302,
    appName: 'EzhavaJodii',
    applicationId: 'ezhava.jodii.com',
    scheme: 'ezhavajodii',
    domain: 'ezhava.jodii.com',
    welcomeText: 'Welcome to Ezhava Jodii',
    icon: './assets/icons/logos/ezhava_jodii.png',
    playStoreUrl: 'https://play.google.com/store/apps/details?id=ezhava.jodii.com',
  },
  nair: {
    appType: 303,
    appName: 'NairJodii',
    applicationId: 'nair.jodii.com',
    scheme: 'nairjodii',
    domain: 'nair.jodii.com',
    welcomeText: 'Welcome to Nair Jodii',
    icon: './assets/icons/logos/nair_jodii.png',
    playStoreUrl: 'https://play.google.com/store/apps/details?id=nair.jodii.com',
  },
  kayastha: {
    appType: 304,
    appName: 'KayasthaJodii',
    applicationId: 'kayastha.jodii.com',
    scheme: 'kayasthajodii',
    domain: 'kayastha.jodii.com',
    welcomeText: 'Welcome to Kayastha Jodii',
    icon: './assets/icons/logos/kayastha_jodii.png',
    playStoreUrl: 'https://play.google.com/store/apps/details?id=kayastha.jodii.com',
  },
  lingayath: {
    appType: 305,
    appName: 'LingayathJodii',
    applicationId: 'lingayath.jodii.com',
    scheme: 'lingayathjodii',
    domain: 'lingayath.jodii.com',
    welcomeText: 'Welcome to Lingayath Jodii',
    icon: './assets/icons/logos/lingayath_jodii.png',
    playStoreUrl: 'https://play.google.com/store/apps/details?id=lingayath.jodii.com',
  },
  khandayat: {
    appType: 306,
    appName: 'KhandayatJodii',
    applicationId: 'khandayat.jodii.com',
    scheme: 'khandayatjodii',
    domain: 'khandayat.jodii.com',
    welcomeText: 'Welcome to Khandayat Jodii',
    icon: './assets/icons/logos/khandayat_jodii.png',
    playStoreUrl: 'https://play.google.com/store/apps/details?id=khandayat.jodii.com',
  },
  sc: {
    appType: 307,
    appName: 'SCJodii',
    applicationId: 'sc.jodii.com',
    scheme: 'scjodii',
    domain: 'sc.jodii.com',
    welcomeText: 'Welcome to SC Jodii',
    icon: './assets/icons/logos/sc_jodii.png',
    playStoreUrl: 'https://play.google.com/store/apps/details?id=sc.jodii.com',
  },
  vokkaliga: {
    appType: 308,
    appName: 'VokkaligaJodii',
    applicationId: 'vokkaliga.jodii.com',
    scheme: 'vokkaligajodii',
    domain: 'vokkaliga.jodii.com',
    welcomeText: 'Welcome to Vokkaliga Jodii',
    icon: './assets/icons/logos/vokkaliga_jodii.png',
    playStoreUrl: 'https://play.google.com/store/apps/details?id=vokkaliga.jodii.com',
  },
  vishwakarma: {
    appType: 309,
    appName: 'VishwakarmaJodii',
    applicationId: 'vishwakarma.jodii.com',
    scheme: 'vishwakarmajodii',
    domain: 'vishwakarma.jodii.com',
    welcomeText: 'Welcome to Vishwakarma Jodii',
    icon: './assets/icons/logos/vishwakarma_jodii.png',
    playStoreUrl: 'https://play.google.com/store/apps/details?id=vishwakarma.jodii.com',
  },
  patel: {
    appType: 310,
    appName: 'PatelJodii',
    applicationId: 'patel.jodii.com',
    scheme: 'pateljodii',
    domain: 'patel.jodii.com',
    welcomeText: 'Welcome to Patel Jodii',
    icon: './assets/icons/logos/patel_jodii.png',
    playStoreUrl: 'https://play.google.com/store/apps/details?id=patel.jodii.com',
  },
  adidravidar: {
    appType: 311,
    appName: 'AdidravidarJodii',
    applicationId: 'adidravidar.jodii.com',
    scheme: 'adidravidarjodii',
    domain: 'adidravidar.jodii.com',
    welcomeText: 'Welcome to Adidravidar Jodii',
    icon: './assets/icons/logos/adidravidar_jodii.png',
    playStoreUrl: 'https://play.google.com/store/apps/details?id=adidravidar.jodii.com',
  },
  teli: {
    appType: 312,
    appName: 'TeliJodii',
    applicationId: 'teli.jodii.com',
    scheme: 'telijodii',
    domain: 'teli.jodii.com',
    welcomeText: 'Welcome to Teli Jodii',
    icon: './assets/icons/logos/teli_jodii.png',
    playStoreUrl: 'https://play.google.com/store/apps/details?id=teli.jodii.com',
  },
  vanniyar: {
    appType: 313,
    appName: 'VanniyarJodii',
    applicationId: 'vanniyar.jodii.com',
    scheme: 'vanniyarjodii',
    domain: 'vanniyar.jodii.com',
    welcomeText: 'Welcome to Vanniyar Jodii',
    icon: './assets/icons/logos/vanniyar_jodii.png',
    playStoreUrl: 'https://play.google.com/store/apps/details?id=vanniyar.jodii.com',
  },
  reddy: {
    appType: 314,
    appName: 'ReddyJodii',
    applicationId: 'reddy.jodii.com',
    scheme: 'reddyjodii',
    domain: 'reddy.jodii.com',
    welcomeText: 'Welcome to Reddy Jodii',
    icon: './assets/icons/logos/reddy_jodii.png',
    playStoreUrl: 'https://play.google.com/store/apps/details?id=reddy.jodii.com',
  },
  kapu: {
    appType: 315,
    appName: 'KapuJodii',
    applicationId: 'kapu.jodii.com',
    scheme: 'kapujodii',
    domain: 'kapu.jodii.com',
    welcomeText: 'Welcome to Kapu Jodii',
    icon: './assets/icons/logos/kapu_jodii.png',
    playStoreUrl: 'https://play.google.com/store/apps/details?id=kapu.jodii.com',
  },
  viswabrahmin: {
    appType: 316,
    appName: 'ViswabrahminJodii',
    applicationId: 'viswabrahmin.jodii.com',
    scheme: 'viswabrahminjodii',
    domain: 'viswabrahmin.jodii.com',
    welcomeText: 'Welcome to Viswabrahmin Jodii',
    icon: './assets/icons/logos/viswabrahmin_jodii.png',
    playStoreUrl: 'https://play.google.com/store/apps/details?id=viswabrahmin.jodii.com',
  },
  thiyya: {
    appType: 317,
    appName: 'ThiyyaJodii',
    applicationId: 'thiyya.jodii.com',
    scheme: 'thiyyajodii',
    domain: 'thiyya.jodii.com',
    welcomeText: 'Welcome to Thiyya Jodii',
    icon: './assets/icons/logos/thiyya_jodii.png',
    playStoreUrl: 'https://play.google.com/store/apps/details?id=thiyya.jodii.com',
  },
  kuruba: {
    appType: 318,
    appName: 'KurubaJodii',
    applicationId: 'kuruba.jodii.com',
    scheme: 'kurubajodii',
    domain: 'kuruba.jodii.com',
    welcomeText: 'Welcome to Kuruba Jodii',
    icon: './assets/icons/logos/kuruba_jodii.png',
    playStoreUrl: 'https://play.google.com/store/apps/details?id=kuruba.jodii.com',
  },
  gowda: {
    appType: 319,
    appName: 'GowdaJodii',
    applicationId: 'gowda.jodii.com',
    scheme: 'gowdajodii',
    domain: 'gowda.jodii.com',
    welcomeText: 'Welcome to Gowda Jodii',
    icon: './assets/icons/logos/gowda_jodii.png',
    playStoreUrl: 'https://play.google.com/store/apps/details?id=gowda.jodii.com',
  },
  nadar: {
    appType: 320,
    appName: 'NadarJodii',
    applicationId: 'nadar.jodii.com',
    scheme: 'nadarjodii',
    domain: 'nadar.jodii.com',
    welcomeText: 'Welcome to Nadar Jodii',
    icon: './assets/icons/logos/nadar_jodii.png',
    playStoreUrl: 'https://play.google.com/store/apps/details?id=nadar.jodii.com',
  },
  aryavysya: {
    appType: 321,
    appName: 'AryavysyaJodii',
    applicationId: 'aryavysya.jodii.com',
    scheme: 'aryavysyajodii',
    domain: 'aryavysya.jodii.com',
    welcomeText: 'Welcome to Aryavysya Jodii',
    icon: './assets/icons/logos/aryavysya_jodii.png',
    playStoreUrl: 'https://play.google.com/store/apps/details?id=aryavysya.jodii.com',
  },
  prajapati: {
    appType: 322,
    appName: 'PrajapatiJodii',
    applicationId: 'prajapati.jodii.com',
    scheme: 'prajapatijodii',
    domain: 'prajapati.jodii.com',
    welcomeText: 'Welcome to Prajapati Jodii',
    icon: './assets/icons/logos/prajapati_jodii.png',
    playStoreUrl: 'https://play.google.com/store/apps/details?id=prajapati.jodii.com',
  },
  konguvellalar: {
    appType: 323,
    appName: 'KonguvellalarJodii',
    applicationId: 'konguvellalar.jodii.com',
    scheme: 'konguvellalarjodii',
    domain: 'konguvellalar.jodii.com',
    welcomeText: 'Welcome to Konguvellalar Jodii',
    icon: './assets/icons/logos/konguvellalar_jodii.png',
    playStoreUrl: 'https://play.google.com/store/apps/details?id=konguvellalar.jodii.com',
  },
  thevar: {
    appType: 324,
    appName: 'ThevarJodii',
    applicationId: 'thevar.jodii.com',
    scheme: 'thevarjodii',
    domain: 'thevar.jodii.com',
    welcomeText: 'Welcome to Thevar Jodii',
    icon: './assets/icons/logos/thevar_jodii.png',
    playStoreUrl: 'https://play.google.com/store/apps/details?id=thevar.jodii.com',
  },
  kshatriya: {
    appType: 325,
    appName: 'KshatriyaJodii',
    applicationId: 'kshatriya.jodii.com',
    scheme: 'kshatriyajodii',
    domain: 'kshatriya.jodii.com',
    welcomeText: 'Welcome to Kshatriya Jodii',
    icon: './assets/icons/logos/kshatriya_jodii.png',
    playStoreUrl: 'https://play.google.com/store/apps/details?id=kshatriya.jodii.com',
  },
  kamma: {
    appType: 326,
    appName: 'KammaJodii',
    applicationId: 'kamma.jodii.com',
    scheme: 'kammajodii',
    domain: 'kamma.jodii.com',
    welcomeText: 'Welcome to Kamma Jodii',
    icon: './assets/icons/logos/kamma_jodii.png',
    playStoreUrl: 'https://play.google.com/store/apps/details?id=kamma.jodii.com',
  },
  rajput: {
    appType: 327,
    appName: 'RajputJodii',
    applicationId: 'rajput.jodii.com',
    scheme: 'rajputjodii',
    domain: 'rajput.jodii.com',
    welcomeText: 'Welcome to Rajput Jodii',
    icon: './assets/icons/logos/rajput_jodii.png',
    playStoreUrl: 'https://play.google.com/store/apps/details?id=rajput.jodii.com',
  },
  agarwal: {
    appType: 328,
    appName: 'AgarwalJodii',
    applicationId: 'agarwal.jodii.com',
    scheme: 'agarwaljodii',
    domain: 'agarwal.jodii.com',
    welcomeText: 'Welcome to Agarwal Jodii',
    icon: './assets/icons/logos/agarwal_jodii.png',
    playStoreUrl: 'https://play.google.com/store/apps/details?id=agarwal.jodii.com',
  },
  yadav: {
    appType: 329,
    appName: 'YadavJodii',
    applicationId: 'yadav.jodii.com',
    scheme: 'yadavjodii',
    domain: 'yadav.jodii.com',
    welcomeText: 'Welcome to Yadav Jodii',
    icon: './assets/icons/logos/yadav_jodii.png',
    playStoreUrl: 'https://play.google.com/store/apps/details?id=yadav.jodii.com',
  },
  mali: {
    appType: 330,
    appName: 'MaliJodii',
    applicationId: 'mali.jodii.com',
    scheme: 'malijodii',
    domain: 'mali.jodii.com',
    welcomeText: 'Welcome to Mali Jodii',
    icon: './assets/icons/logos/mali_jodii.png',
    playStoreUrl: 'https://play.google.com/store/apps/details?id=mali.jodii.com',
  },
  st: {
    appType: 331,
    appName: 'STJodii',
    applicationId: 'st.jodii.com',
    scheme: 'stjodii',
    domain: 'st.jodii.com',
    welcomeText: 'Welcome to ST Jodii',
    icon: './assets/icons/logos/st_jodii.png',
    playStoreUrl: 'https://play.google.com/store/apps/details?id=st.jodii.com',
  },
  naidu: {
    appType: 332,
    appName: 'NaiduJodii',
    applicationId: 'naidu.jodii.com',
    scheme: 'naidujodii',
    domain: 'naidu.jodii.com',
    welcomeText: 'Welcome to Naidu Jodii',
    icon: './assets/icons/logos/naidu_jodii.png',
    playStoreUrl: 'https://play.google.com/store/apps/details?id=naidu.jodii.com',
  },
  mudaliyar: {
    appType: 333,
    appName: 'MudaliyarJodii',
    applicationId: 'mudaliyar.jodii.com',
    scheme: 'mudaliyarjodii',
    domain: 'mudaliyar.jodii.com',
    welcomeText: 'Welcome to Mudaliyar Jodii',
    icon: './assets/icons/logos/mudaliyar_jodii.png',
    playStoreUrl: 'https://play.google.com/store/apps/details?id=mudaliyar.jodii.com',
  },
  chettiyar: {
    appType: 334,
    appName: 'ChettiyarJodii',
    applicationId: 'chettiyar.jodii.com',
    scheme: 'chettiyarjodii',
    domain: 'chettiyar.jodii.com',
    welcomeText: 'Welcome to Chettiyar Jodii',
    icon: './assets/icons/logos/chettiyar_jodii.png',
    playStoreUrl: 'https://play.google.com/store/apps/details?id=chettiyar.jodii.com',
  },
  padmasali: {
    appType: 335,
    appName: 'PadmasaliJodii',
    applicationId: 'padmasali.jodii.com',
    scheme: 'padmasalijodii',
    domain: 'padmasali.jodii.com',
    welcomeText: 'Welcome to Padmasali Jodii',
    icon: './assets/icons/logos/padmasali_jodii.png',
    playStoreUrl: 'https://play.google.com/store/apps/details?id=padmasali.jodii.com',
  },
  jat: {
    appType: 336,
    appName: 'JatJodii',
    applicationId: 'jat.jodii.com',
    scheme: 'jatjodii',
    domain: 'jat.jodii.com',
    welcomeText: 'Welcome to Jat Jodii',
    icon: './assets/icons/logos/jat_jodii.png',
    playStoreUrl: 'https://play.google.com/store/apps/details?id=jat.jodii.com',
  },
  baniya: {
    appType: 337,
    appName: 'BaniyaJodii',
    applicationId: 'baniya.jodii.com',
    scheme: 'baniyajodii',
    domain: 'baniya.jodii.com',
    welcomeText: 'Welcome to Baniya Jodii',
    icon: './assets/icons/logos/baniya_jodii.png',
    playStoreUrl: 'https://play.google.com/store/apps/details?id=baniya.jodii.com',
  },
  pillai: {
    appType: 338,
    appName: 'PillaiJodii',
    applicationId: 'pillai.jodii.com',
    scheme: 'pillaijodii',
    domain: 'pillai.jodii.com',
    welcomeText: 'Welcome to Pillai Jodii',
    icon: './assets/icons/logos/pillai_jodii.png',
    playStoreUrl: 'https://play.google.com/store/apps/details?id=pillai.jodii.com',
  },
  brahmin: {
    appType: 504,
    appName: 'BrahminJodii',
    applicationId: 'brahmin.jodii.com',
    scheme: 'brahminjodii',
    domain: 'brahmin.jodii.com',
    welcomeText: 'Welcome to Brahmin Jodii',
    icon: './assets/icons/logos/brahmin_jodii.png',
    playStoreUrl: 'https://play.google.com/store/apps/details?id=brahmin.jodii.com',
  },
  christian: {
    appType: 501,
    appName: 'ChristianJodii',
    applicationId: 'christian.jodii.com',
    scheme: 'christianjodii',
    domain: 'christian.jodii.com',
    welcomeText: 'Welcome to Christian Jodii',
    icon: './assets/icons/logos/christian_jodii.png',
    playStoreUrl: 'https://play.google.com/store/apps/details?id=christian.jodii.com',
  },
  muslim: {
    appType: 502,
    appName: 'MuslimJodii',
    applicationId: 'muslim.jodii.com',
    scheme: 'muslimjodii',
    domain: 'muslim.jodii.com',
    welcomeText: 'Welcome to Muslim Jodii',
    icon: './assets/icons/logos/muslim_jodii.png',
    playStoreUrl: 'https://play.google.com/store/apps/details?id=muslim.jodii.com',
  },
  divorcee: {
    appType: 503,
    appName: 'DivorceeJodii',
    applicationId: 'divorcee.jodii.com',
    scheme: 'divorceejodii',
    domain: 'divorcee.jodii.com',
    welcomeText: 'Welcome to Divorcee Jodii',
    icon: './assets/icons/logos/divorcee_jodii.png',
    playStoreUrl: 'https://play.google.com/store/apps/details?id=divorcee.jodii.com',
  },
  jain: {
    appType: 505,
    appName: 'JainJodii',
    applicationId: 'jain.jodii.com',
    scheme: 'jainjodii',
    domain: 'jain.jodii.com',
    welcomeText: 'Welcome to Jain Jodii',
    icon: './assets/icons/logos/jain_jodii.png',
    playStoreUrl: 'https://play.google.com/store/apps/details?id=jain.jodii.com',
  },
  sikh: {
    appType: 506,
    appName: 'SikhJodii',
    applicationId: 'sikh.jodii.com',
    scheme: 'sikhjodii',
    domain: 'sikh.jodii.com',
    welcomeText: 'Welcome to Sikh Jodii',
    icon: './assets/icons/logos/sikh_jodii.png',
    playStoreUrl: 'https://play.google.com/store/apps/details?id=sikh.jodii.com',
  },
};

module.exports = FLAVORS;
