const FLAVORS = {
  jodii: {
    appType: 115,
    appName: 'Jodii',
    applicationId: 'jodii.app',
    scheme: 'jodii',
    domain: 'jodii.app',
    welcomeText: 'Welcome to Jodii',
    icon: './assets/icon.png',
    playStoreUrl: 'https://play.google.com/store/apps/details?id=jodii.app&hl=en_US&gl=US',
  },
  tamil: {
    appType: 116,
    appName: 'Tamil Jodii',
    applicationId: 'jodiiapp.android.tamil',
    scheme: 'tamilmatrimony',
    domain: 'tamil.jodii.app',
    welcomeText: 'Welcome to Tamil Jodii',
    icon: './assets/icons/logos/tamil_jodii.png',
    playStoreUrl: 'https://play.google.com/store/apps/details?id=jodiiapp.android.tamil',
  },
  malayalam: {
    appType: 118,
    appName: 'Malayalam Jodii',
    applicationId: 'jodiiapp.android.malayalam',
    scheme: 'malayalammatrimony',
    domain: 'malayalam.jodii.app',
    welcomeText: 'Welcome to Malayalam Jodii',
    icon: './assets/icons/logos/malayalam_jodii.png',
    playStoreUrl: 'https://play.google.com/store/apps/details?id=jodiiapp.android.malayalam',
  },
  // Remaining flavors ported from the old native Android project's
  // build.gradle.kts.jinja (productFlavors, dimension "app"). Keys use this
  // project's shortened-name convention (matching jodii/tamil/malayalam
  // above) rather than the native project's raw flavor names (e.g.
  // "brahminjodii") — applicationId/appType are copied verbatim from there.
  // icon left as the generic Jodii icon as a placeholder — real per-flavor
  // icons to be swapped in later.
  telugu: {
    appType: 117,
    appName: 'Telugu Jodii',
    applicationId: 'jodiiapp.android.telugu',
    scheme: 'telugujodii',
    domain: 'telugu.jodii.app',
    welcomeText: 'Welcome to Telugu Jodii',
    icon: './assets/icon.png',
    playStoreUrl: 'https://play.google.com/store/apps/details?id=jodiiapp.android.telugu',
  },
  kannada: {
    appType: 119,
    appName: 'Kannada Jodii',
    applicationId: 'jodiiapp.android.kannada',
    scheme: 'kannadajodii',
    domain: 'kannada.jodii.app',
    welcomeText: 'Welcome to Kannada Jodii',
    icon: './assets/icon.png',
    playStoreUrl: 'https://play.google.com/store/apps/details?id=jodiiapp.android.kannada',
  },
  oriya: {
    appType: 120,
    appName: 'Oriya Jodii',
    applicationId: 'jodiiapp.android.oriya',
    scheme: 'oriyajodii',
    domain: 'oriya.jodii.app',
    welcomeText: 'Welcome to Oriya Jodii',
    icon: './assets/icon.png',
    playStoreUrl: 'https://play.google.com/store/apps/details?id=jodiiapp.android.oriya',
  },
  bengali: {
    appType: 121,
    appName: 'Bengali Jodii',
    applicationId: 'jodiiapp.android.bengali',
    scheme: 'bengalijodii',
    domain: 'bengali.jodii.app',
    welcomeText: 'Welcome to Bengali Jodii',
    icon: './assets/icon.png',
    playStoreUrl: 'https://play.google.com/store/apps/details?id=jodiiapp.android.bengali',
  },
  marathi: {
    appType: 122,
    appName: 'Marathi Jodii',
    applicationId: 'jodiiapp.android.marathi',
    scheme: 'marathijodii',
    domain: 'marathi.jodii.app',
    welcomeText: 'Welcome to Marathi Jodii',
    icon: './assets/icon.png',
    playStoreUrl: 'https://play.google.com/store/apps/details?id=jodiiapp.android.marathi',
  },
  gujarati: {
    appType: 123,
    appName: 'Gujarati Jodii',
    applicationId: 'jodiiapp.android.gujarati',
    scheme: 'gujarathijodii',
    domain: 'gujarati.jodii.app',
    welcomeText: 'Welcome to Gujarati Jodii',
    icon: './assets/icon.png',
    playStoreUrl: 'https://play.google.com/store/apps/details?id=jodiiapp.android.gujarati',
  },
  hindi: {
    appType: 124,
    appName: 'Hindi Jodii',
    applicationId: 'jodiiapp.android.hindi',
    scheme: 'hindijodii',
    domain: 'hindi.jodii.app',
    welcomeText: 'Welcome to Hindi Jodii',
    icon: './assets/icon.png',
    playStoreUrl: 'https://play.google.com/store/apps/details?id=jodiiapp.android.hindi',
  },
  punjabi: {
    appType: 125,
    appName: 'Punjabi Jodii',
    applicationId: 'jodiiapp.android.punjabi',
    scheme: 'punjabijodii',
    domain: 'punjabi.jodii.app',
    welcomeText: 'Welcome to Punjabi Jodii',
    icon: './assets/icon.png',
    playStoreUrl: 'https://play.google.com/store/apps/details?id=jodiiapp.android.punjabi',
  },
  ninetysixkulimaratha: {
    appType: 301,
    appName: 'Ninetysixkulimaratha Jodii',
    applicationId: 'ninetysixkulimaratha.jodii.com',
    scheme: 'ninetysixkulimaratha',
    domain: 'ninetysixkulimaratha.jodii.com',
    welcomeText: 'Welcome to Ninetysixkulimaratha Jodii',
    icon: './assets/icon.png',
    playStoreUrl: 'https://play.google.com/store/apps/details?id=ninetysixkulimaratha.jodii.com',
  },
  ezhava: {
    appType: 302,
    appName: 'Ezhava Jodii',
    applicationId: 'ezhava.jodii.com',
    scheme: 'ezhavajodii',
    domain: 'ezhava.jodii.com',
    welcomeText: 'Welcome to Ezhava Jodii',
    icon: './assets/icon.png',
    playStoreUrl: 'https://play.google.com/store/apps/details?id=ezhava.jodii.com',
  },
  nair: {
    appType: 303,
    appName: 'Nair Jodii',
    applicationId: 'nair.jodii.com',
    scheme: 'nairjodii',
    domain: 'nair.jodii.com',
    welcomeText: 'Welcome to Nair Jodii',
    icon: './assets/icon.png',
    playStoreUrl: 'https://play.google.com/store/apps/details?id=nair.jodii.com',
  },
  kayastha: {
    appType: 304,
    appName: 'Kayastha Jodii',
    applicationId: 'kayastha.jodii.com',
    scheme: 'kayasthajodii',
    domain: 'kayastha.jodii.com',
    welcomeText: 'Welcome to Kayastha Jodii',
    icon: './assets/icon.png',
    playStoreUrl: 'https://play.google.com/store/apps/details?id=kayastha.jodii.com',
  },
  lingayath: {
    appType: 305,
    appName: 'Lingayath Jodii',
    applicationId: 'lingayath.jodii.com',
    scheme: 'lingayathjodii',
    domain: 'lingayath.jodii.com',
    welcomeText: 'Welcome to Lingayath Jodii',
    icon: './assets/icon.png',
    playStoreUrl: 'https://play.google.com/store/apps/details?id=lingayath.jodii.com',
  },
  khandayat: {
    appType: 306,
    appName: 'Khandayat Jodii',
    applicationId: 'khandayat.jodii.com',
    scheme: 'khandayatjodii',
    domain: 'khandayat.jodii.com',
    welcomeText: 'Welcome to Khandayat Jodii',
    icon: './assets/icon.png',
    playStoreUrl: 'https://play.google.com/store/apps/details?id=khandayat.jodii.com',
  },
  sc: {
    appType: 307,
    appName: 'SC Jodii',
    applicationId: 'sc.jodii.com',
    scheme: 'scjodii',
    domain: 'sc.jodii.com',
    welcomeText: 'Welcome to SC Jodii',
    icon: './assets/icon.png',
    playStoreUrl: 'https://play.google.com/store/apps/details?id=sc.jodii.com',
  },
  vokkaliga: {
    appType: 308,
    appName: 'Vokkaliga Jodii',
    applicationId: 'vokkaliga.jodii.com',
    scheme: 'vokkaligajodii',
    domain: 'vokkaliga.jodii.com',
    welcomeText: 'Welcome to Vokkaliga Jodii',
    icon: './assets/icon.png',
    playStoreUrl: 'https://play.google.com/store/apps/details?id=vokkaliga.jodii.com',
  },
  vishwakarma: {
    appType: 309,
    appName: 'Vishwakarma Jodii',
    applicationId: 'vishwakarma.jodii.com',
    scheme: 'vishwakarmajodii',
    domain: 'vishwakarma.jodii.com',
    welcomeText: 'Welcome to Vishwakarma Jodii',
    icon: './assets/icon.png',
    playStoreUrl: 'https://play.google.com/store/apps/details?id=vishwakarma.jodii.com',
  },
  patel: {
    appType: 310,
    appName: 'Patel Jodii',
    applicationId: 'patel.jodii.com',
    scheme: 'pateljodii',
    domain: 'patel.jodii.com',
    welcomeText: 'Welcome to Patel Jodii',
    icon: './assets/icon.png',
    playStoreUrl: 'https://play.google.com/store/apps/details?id=patel.jodii.com',
  },
  adidravidar: {
    appType: 311,
    appName: 'Adidravidar Jodii',
    applicationId: 'adidravidar.jodii.com',
    scheme: 'adidravidarjodii',
    domain: 'adidravidar.jodii.com',
    welcomeText: 'Welcome to Adidravidar Jodii',
    icon: './assets/icon.png',
    playStoreUrl: 'https://play.google.com/store/apps/details?id=adidravidar.jodii.com',
  },
  teli: {
    appType: 312,
    appName: 'Teli Jodii',
    applicationId: 'teli.jodii.com',
    scheme: 'telijodii',
    domain: 'teli.jodii.com',
    welcomeText: 'Welcome to Teli Jodii',
    icon: './assets/icon.png',
    playStoreUrl: 'https://play.google.com/store/apps/details?id=teli.jodii.com',
  },
  vanniyar: {
    appType: 313,
    appName: 'Vanniyar Jodii',
    applicationId: 'vanniyar.jodii.com',
    scheme: 'vanniyarjodii',
    domain: 'vanniyar.jodii.com',
    welcomeText: 'Welcome to Vanniyar Jodii',
    icon: './assets/icon.png',
    playStoreUrl: 'https://play.google.com/store/apps/details?id=vanniyar.jodii.com',
  },
  reddy: {
    appType: 314,
    appName: 'Reddy Jodii',
    applicationId: 'reddy.jodii.com',
    scheme: 'reddyjodii',
    domain: 'reddy.jodii.com',
    welcomeText: 'Welcome to Reddy Jodii',
    icon: './assets/icon.png',
    playStoreUrl: 'https://play.google.com/store/apps/details?id=reddy.jodii.com',
  },
  kapu: {
    appType: 315,
    appName: 'Kapu Jodii',
    applicationId: 'kapu.jodii.com',
    scheme: 'kapujodii',
    domain: 'kapu.jodii.com',
    welcomeText: 'Welcome to Kapu Jodii',
    icon: './assets/icon.png',
    playStoreUrl: 'https://play.google.com/store/apps/details?id=kapu.jodii.com',
  },
  viswabrahmin: {
    appType: 316,
    appName: 'Viswabrahmin Jodii',
    applicationId: 'viswabrahmin.jodii.com',
    scheme: 'viswabrahminjodii',
    domain: 'viswabrahmin.jodii.com',
    welcomeText: 'Welcome to Viswabrahmin Jodii',
    icon: './assets/icon.png',
    playStoreUrl: 'https://play.google.com/store/apps/details?id=viswabrahmin.jodii.com',
  },
  thiyya: {
    appType: 317,
    appName: 'Thiyya Jodii',
    applicationId: 'thiyya.jodii.com',
    scheme: 'thiyyajodii',
    domain: 'thiyya.jodii.com',
    welcomeText: 'Welcome to Thiyya Jodii',
    icon: './assets/icon.png',
    playStoreUrl: 'https://play.google.com/store/apps/details?id=thiyya.jodii.com',
  },
  kuruba: {
    appType: 318,
    appName: 'Kuruba Jodii',
    applicationId: 'kuruba.jodii.com',
    scheme: 'kurubajodii',
    domain: 'kuruba.jodii.com',
    welcomeText: 'Welcome to Kuruba Jodii',
    icon: './assets/icon.png',
    playStoreUrl: 'https://play.google.com/store/apps/details?id=kuruba.jodii.com',
  },
  gowda: {
    appType: 319,
    appName: 'Gowda Jodii',
    applicationId: 'gowda.jodii.com',
    scheme: 'gowdajodii',
    domain: 'gowda.jodii.com',
    welcomeText: 'Welcome to Gowda Jodii',
    icon: './assets/icon.png',
    playStoreUrl: 'https://play.google.com/store/apps/details?id=gowda.jodii.com',
  },
  nadar: {
    appType: 320,
    appName: 'Nadar Jodii',
    applicationId: 'nadar.jodii.com',
    scheme: 'nadarjodii',
    domain: 'nadar.jodii.com',
    welcomeText: 'Welcome to Nadar Jodii',
    icon: './assets/icon.png',
    playStoreUrl: 'https://play.google.com/store/apps/details?id=nadar.jodii.com',
  },
  aryavysya: {
    appType: 321,
    appName: 'Aryavysya Jodii',
    applicationId: 'aryavysya.jodii.com',
    scheme: 'aryavysyajodii',
    domain: 'aryavysya.jodii.com',
    welcomeText: 'Welcome to Aryavysya Jodii',
    icon: './assets/icon.png',
    playStoreUrl: 'https://play.google.com/store/apps/details?id=aryavysya.jodii.com',
  },
  prajapati: {
    appType: 322,
    appName: 'Prajapati Jodii',
    applicationId: 'prajapati.jodii.com',
    scheme: 'prajapatijodii',
    domain: 'prajapati.jodii.com',
    welcomeText: 'Welcome to Prajapati Jodii',
    icon: './assets/icon.png',
    playStoreUrl: 'https://play.google.com/store/apps/details?id=prajapati.jodii.com',
  },
  konguvellalar: {
    appType: 323,
    appName: 'Konguvellalar Jodii',
    applicationId: 'konguvellalar.jodii.com',
    scheme: 'konguvellalarjodii',
    domain: 'konguvellalar.jodii.com',
    welcomeText: 'Welcome to Konguvellalar Jodii',
    icon: './assets/icon.png',
    playStoreUrl: 'https://play.google.com/store/apps/details?id=konguvellalar.jodii.com',
  },
  thevar: {
    appType: 324,
    appName: 'Thevar Jodii',
    applicationId: 'thevar.jodii.com',
    scheme: 'thevarjodii',
    domain: 'thevar.jodii.com',
    welcomeText: 'Welcome to Thevar Jodii',
    icon: './assets/icon.png',
    playStoreUrl: 'https://play.google.com/store/apps/details?id=thevar.jodii.com',
  },
  kshatriya: {
    appType: 325,
    appName: 'Kshatriya Jodii',
    applicationId: 'kshatriya.jodii.com',
    scheme: 'kshatriyajodii',
    domain: 'kshatriya.jodii.com',
    welcomeText: 'Welcome to Kshatriya Jodii',
    icon: './assets/icon.png',
    playStoreUrl: 'https://play.google.com/store/apps/details?id=kshatriya.jodii.com',
  },
  kamma: {
    appType: 326,
    appName: 'Kamma Jodii',
    applicationId: 'kamma.jodii.com',
    scheme: 'kammajodii',
    domain: 'kamma.jodii.com',
    welcomeText: 'Welcome to Kamma Jodii',
    icon: './assets/icon.png',
    playStoreUrl: 'https://play.google.com/store/apps/details?id=kamma.jodii.com',
  },
  rajput: {
    appType: 327,
    appName: 'Rajput Jodii',
    applicationId: 'rajput.jodii.com',
    scheme: 'rajputjodii',
    domain: 'rajput.jodii.com',
    welcomeText: 'Welcome to Rajput Jodii',
    icon: './assets/icon.png',
    playStoreUrl: 'https://play.google.com/store/apps/details?id=rajput.jodii.com',
  },
  agarwal: {
    appType: 328,
    appName: 'Agarwal Jodii',
    applicationId: 'agarwal.jodii.com',
    scheme: 'agarwaljodii',
    domain: 'agarwal.jodii.com',
    welcomeText: 'Welcome to Agarwal Jodii',
    icon: './assets/icon.png',
    playStoreUrl: 'https://play.google.com/store/apps/details?id=agarwal.jodii.com',
  },
  yadav: {
    appType: 329,
    appName: 'Yadav Jodii',
    applicationId: 'yadav.jodii.com',
    scheme: 'yadavjodii',
    domain: 'yadav.jodii.com',
    welcomeText: 'Welcome to Yadav Jodii',
    icon: './assets/icon.png',
    playStoreUrl: 'https://play.google.com/store/apps/details?id=yadav.jodii.com',
  },
  mali: {
    appType: 330,
    appName: 'Mali Jodii',
    applicationId: 'mali.jodii.com',
    scheme: 'malijodii',
    domain: 'mali.jodii.com',
    welcomeText: 'Welcome to Mali Jodii',
    icon: './assets/icon.png',
    playStoreUrl: 'https://play.google.com/store/apps/details?id=mali.jodii.com',
  },
  st: {
    appType: 331,
    appName: 'ST Jodii',
    applicationId: 'st.jodii.com',
    scheme: 'stjodii',
    domain: 'st.jodii.com',
    welcomeText: 'Welcome to ST Jodii',
    icon: './assets/icon.png',
    playStoreUrl: 'https://play.google.com/store/apps/details?id=st.jodii.com',
  },
  naidu: {
    appType: 332,
    appName: 'Naidu Jodii',
    applicationId: 'naidu.jodii.com',
    scheme: 'naidujodii',
    domain: 'naidu.jodii.com',
    welcomeText: 'Welcome to Naidu Jodii',
    icon: './assets/icon.png',
    playStoreUrl: 'https://play.google.com/store/apps/details?id=naidu.jodii.com',
  },
  mudaliyar: {
    appType: 333,
    appName: 'Mudaliyar Jodii',
    applicationId: 'mudaliyar.jodii.com',
    scheme: 'mudaliyarjodii',
    domain: 'mudaliyar.jodii.com',
    welcomeText: 'Welcome to Mudaliyar Jodii',
    icon: './assets/icon.png',
    playStoreUrl: 'https://play.google.com/store/apps/details?id=mudaliyar.jodii.com',
  },
  chettiyar: {
    appType: 334,
    appName: 'Chettiyar Jodii',
    applicationId: 'chettiyar.jodii.com',
    scheme: 'chettiyarjodii',
    domain: 'chettiyar.jodii.com',
    welcomeText: 'Welcome to Chettiyar Jodii',
    icon: './assets/icon.png',
    playStoreUrl: 'https://play.google.com/store/apps/details?id=chettiyar.jodii.com',
  },
  padmasali: {
    appType: 335,
    appName: 'Padmasali Jodii',
    applicationId: 'padmasali.jodii.com',
    scheme: 'padmasalijodii',
    domain: 'padmasali.jodii.com',
    welcomeText: 'Welcome to Padmasali Jodii',
    icon: './assets/icon.png',
    playStoreUrl: 'https://play.google.com/store/apps/details?id=padmasali.jodii.com',
  },
  jat: {
    appType: 336,
    appName: 'Jat Jodii',
    applicationId: 'jat.jodii.com',
    scheme: 'jatjodii',
    domain: 'jat.jodii.com',
    welcomeText: 'Welcome to Jat Jodii',
    icon: './assets/icon.png',
    playStoreUrl: 'https://play.google.com/store/apps/details?id=jat.jodii.com',
  },
  baniya: {
    appType: 337,
    appName: 'Baniya Jodii',
    applicationId: 'baniya.jodii.com',
    scheme: 'baniyajodii',
    domain: 'baniya.jodii.com',
    welcomeText: 'Welcome to Baniya Jodii',
    icon: './assets/icon.png',
    playStoreUrl: 'https://play.google.com/store/apps/details?id=baniya.jodii.com',
  },
  pillai: {
    appType: 338,
    appName: 'Pillai Jodii',
    applicationId: 'pillai.jodii.com',
    scheme: 'pillaijodii',
    domain: 'pillai.jodii.com',
    welcomeText: 'Welcome to Pillai Jodii',
    icon: './assets/icon.png',
    playStoreUrl: 'https://play.google.com/store/apps/details?id=pillai.jodii.com',
  },
  brahmin: {
    appType: 504,
    appName: 'Brahmin Jodii',
    applicationId: 'brahmin.jodii.com',
    scheme: 'brahminjodii',
    domain: 'brahmin.jodii.com',
    welcomeText: 'Welcome to Brahmin Jodii',
    icon: './assets/icon.png',
    playStoreUrl: 'https://play.google.com/store/apps/details?id=brahmin.jodii.com',
  },
  christian: {
    appType: 501,
    appName: 'Christian Jodii',
    applicationId: 'christian.jodii.com',
    scheme: 'christianjodii',
    domain: 'christian.jodii.com',
    welcomeText: 'Welcome to Christian Jodii',
    icon: './assets/icon.png',
    playStoreUrl: 'https://play.google.com/store/apps/details?id=christian.jodii.com',
  },
  muslim: {
    appType: 502,
    appName: 'Muslim Jodii',
    applicationId: 'muslim.jodii.com',
    scheme: 'muslimjodii',
    domain: 'muslim.jodii.com',
    welcomeText: 'Welcome to Muslim Jodii',
    icon: './assets/icon.png',
    playStoreUrl: 'https://play.google.com/store/apps/details?id=muslim.jodii.com',
  },
  divorcee: {
    appType: 503,
    appName: 'Divorcee Jodii',
    applicationId: 'divorcee.jodii.com',
    scheme: 'divorceejodii',
    domain: 'divorcee.jodii.com',
    welcomeText: 'Welcome to Divorcee Jodii',
    icon: './assets/icon.png',
    playStoreUrl: 'https://play.google.com/store/apps/details?id=divorcee.jodii.com',
  },
  jain: {
    appType: 505,
    appName: 'Jain Jodii',
    applicationId: 'jain.jodii.com',
    scheme: 'jainjodii',
    domain: 'jain.jodii.com',
    welcomeText: 'Welcome to Jain Jodii',
    icon: './assets/icon.png',
    playStoreUrl: 'https://play.google.com/store/apps/details?id=jain.jodii.com',
  },
  sikh: {
    appType: 506,
    appName: 'Sikh Jodii',
    applicationId: 'sikh.jodii.com',
    scheme: 'sikhjodii',
    domain: 'sikh.jodii.com',
    welcomeText: 'Welcome to Sikh Jodii',
    icon: './assets/icon.png',
    playStoreUrl: 'https://play.google.com/store/apps/details?id=sikh.jodii.com',
  },
};

module.exports = FLAVORS;
