// All AsyncStorage keys grouped by domain.
// Old Angular constants.ts had 104+ flat exports — grouped here for clarity.
export const StorageKeys = {

  Auth: {
    TOKEN:         'ATN',          // access token
    REFRESH_TOKEN: 'RTN',          // refresh token
    USER_ID:       'NBID',         // logged-in user ID
    LOGIN_COUNT:   'LOGINCOUNT',
    WEB_LOGIN:     'WEBLOGIN',
    APP_TYPE:      'APPTYPE',
    ENTRY_TYPE:    'ENTRYTYPE',
    LANG:          'LANG',
  },

  User: {
    NAME: 'NAME',
    GENDER: 'GENDER',
    LOGIN_GENDER: 'LOGINGENDER',
    PHOTO_URL: 'PHOTOURL',
    COUNTRY_CODE: 'CCODE',
    MEMBER_CODE: 'MCODE',
    MEMBERSHIP_TYPE: 'MEMBERSHIPTYPE',
    TIME_CREATED: 'TIMECREATED',
    DATE_OF_BIRTH: 'DATEOFBIRTH',
    LAST_LOGIN: 'LASTLOGIN',
    CREATED_BY: 'CREATEDBY',
    MOTHER_TONGUE: 'MOTHERTOUNGE',
    OCCUPATION: 'OCCUPATION',
    INCOME: 'INCOME',
    BROTHERS: 'BROTHERS',
    SISTERS: 'SISTERS',
    FAMILY_PROPERTY: 'FAMILYPROPERTY',
  },

  Profile: {
    PHOTO_PRIVACY: 'PHOTOPRIVACY',
    MOBILE_PRIVACY: 'MOBILEPRIVACY',
    PHOTO_STATUS_ARRAY: 'PHOTOSTATUSARRAY',
    PROFILE_VERIFIED: 'PROFILEVERIFIED',
    HOROSCOPE_AVAILABLE: 'HOROSCOPEAVAILABLE',
    STAR: 'STAR',
    RAASI: 'RAASI',
    DOSHAM: 'DOSHAM',
    NRI_WHATSAPP: 'NRIWHATSAPP',
    IP_COUNTRY_CODE: 'IPCOUNTRYCODE',
    NON_IDV_USER_TYPE: 'NONIDVUTYPE',
  },

  Verification: {
    EKYC_STATUS: 'EKYCSTATUS',
    PHONE_VERIFIED: 'PHONEVERIFIED',
    ID_PROOF_UPDATE: 'IDPROOFUPDATE',
    TRUECALL_VERIFY: 'TRUECALLVERIFY',
    ID_VERIFY_CS_NUMBER: 'IDVERIFYCSNUMBER',
    SIGNZY_KEY: 'SIGNZYKEY',
    DEFERRED_ID_USER: 'DEFERREDIDUSER',
  },

  Payment: {
    PAYMENT_WALL: 'PAYMENTWALL',
    PAY_PROMO: 'PAYPROMO',
    RENEWAL_DAY: 'RENEWALDAY',
    PAY_RENEWAL_FLAG: 'PAYRENEWALFLAG',
    RPAY_FLAG: 'RPAYFLAG',
    UPI_FLAG: 'UPIFLAG',
    UPI_APPS: 'UPIAPPS',
    PAY_API_TYPE: 'PAYAPITYPE',
    PAY_P_FLAG: 'PAYPFLAG',
    BP_KEY: 'BPK',
    BP_DATA: 'BPD',
    RP: 'RP',
    STT: 'STT',
    FUPI: 'FUPI',
    RECHARGE_HELPLINE: 'RECHARGEHELPLINE',
  },

  Promotions: {
    FREE_TRIAL_EXTEND: 'FREETRIALEXTEND',
    FREE_TRIAL_EXTEND_DAY: 'FREETRAILEXTENDAY',
    FREE_TRIAL_VALID_DAY: 'FREETRAILVALIDDAY',
    AADHAR_PROMO: 'AADHARPROMO',
    ADD_PHOTO_PROMO: 'ADDPHOTOPROMO',
    FEMALE_FREE_CONTACT: 'FEMALEFREECONACT',
    FEMALE_FREE_PROMO: 'FEMALEFREEPROMO',
    RENEWAL_PROMO_KEY: 'RENEWALPROMOKEY',
    RENEWAL_ENABLE_KEY: 'RENEWALENABLEKEY',
    SF_PROMOTION: 'S&FPROMOTION',
    CR_FLAG: 'CRFLAG',
    // Angular: explore.component.ts's local dismissal of the Home "assist" banner
    // (persisted once the user taps its CTA/close) — ASSISTEDPROMO=='1' means don't
    // show it again this session even if PPSET's ASSISTEDFLAG is still '1'.
    ASSISTED_PROMO: 'ASSISTEDPROMO',
  },

  Faq: {
    FAQ_AVAILABLE: 'FAQAVAILABLE',
    FAQ_TYPE: 'FAQTYPE',
    FAQ_VIDEO_TOUCHPOINT: 'FAQVIDEOTOUCHPOINT',
    FAQ_MATCHES_TOUCHPOINT: 'FAQMATCHESTOUCHPOINT',
  },

  App: {
    DYNAMIC: 'DYNAMIC',
    PP_SET_DATA: 'PPSETDATA',
    APP_VERSION: 'APPVERSION',
    ACTION_TYPE: 'ACTIONTYPE',
    SURVEY_POPUP: 'SURVEYPOPUP',
    REFERRAL_TYPE: 'REFERRALTYPE',
    REFERRAL_FLAG: 'REFERRALFLAG',
    GLASSBOX_FLAG: 'GLASSBOXFLAG',
    SVK: 'SVK',
    IN_APP_MSG_TYPE: 'INAPPMSGTYPE',
    MSG_TYPE: 'MSGTYPE',
    BLOCKER: 'BLOCKER',
    NALLOW: 'NALLOW',
    ILV: 'ILV',
    PLC: 'PLC',
    L_REMOVE: 'LRemove',
    WA_PHOTO_FLAG: 'WAPHOTOFLAG',
    WA_DEPRI: 'WADEPRI',
    DR_NEXT: 'DRNEXT',
    EPR_FLAG: 'EPRFLAG',
    ID_UPLOAD_NUM: 'IDUPLOADNUM',
    RELIGION_KEY: 'RELIGIONKEY',
    CUSTOMER_CARE: 'CUSTOMER-CARE',
    BIODATA_THEME_ID: 'THEMEID',
    TEST: 'TEST',
  },

} as const
