// Screen route names — use these everywhere instead of raw strings.
// Maps 1:1 to React Navigation screen names.
export enum ENavigation {
  LOGIN = 'login',
  OTP = 'otp',
  WELCOME = 'welcome',
  REGISTRATION = 'registration',
  FILTER = 'filter',
  LOGOUT = 'logout',
  DASHBOARD = 'dashboard',
  VIEW_PROFILE = 'viewProfile',
  SETUP = 'setup',
  SELFIE_VERIFICATION = 'selfie-verification',
  GALLERY = 'gallery',
  ACTIVITY = 'activity',
  MATCHES = 'matches',
  DASHBOARD_MATCHES = 'dashboard-matches',
  MESSAGES = 'messages',
  CHAT_LIST = 'chatlist',
  NOTIFICATION = 'notification',
  PROFILE_SETTING = 'profile-setting',
  BASIC_INFO = 'basic-info',
  RELIGION_INFO = 'religion-info',
  LIFE_STYLE = 'life-style',
  PROMPT = 'prompt',
  EDIT_PROFILE = 'edit-profile',
  DRAFT = 'draft',
  PHOTO_UPLOAD = 'photo-upload',
  PROMPT_TAB = 'prompt-tab',
  PROMPT_SELECTION = 'prompt-select',
  ID_VERIFICATION = 'id-verification',
  USER_PREFERENCE = 'user-preference',
  REFERRAL = 'referral',
  CHAT_ROOM = 'chat-room',
  EDIT_BREATHERS = 'editprofile-breathers',
  FILTER_PREFERENCE_DETAILS = 'filter-preference-details',
  PREFERENCE = 'preference',
  HOBBIES = 'hobbies',
  TERMS = 'terms',
  PRIVACY = 'privacy',
  UPLOAD_PHOTO = 'upload_photo',
  EDIT_PHOTO = 'edit_photo',
  HELP_CENTER = 'help-center',
  RELIGIOUS_INFORMATION = 'religious-information',
  PROFILE_HOLD = 'profile-hold',
  PAYMENT_DETAILS = 'payment-details',
  PRELAUNCH_WELCOME = 'prelaunch-welcome',
  MEMBERSHIP_DETAILS = 'membership-details',
  PAYMENT_OPTIONS = 'payment-options',

  // ─── Jodii-specific screens ──────────────────────────────────────────────
  DAILY_RECOMMENDATIONS  = 'daily-recommendations',
  ONBOARDING             = 'onboarding',
  EDIT_FORM              = 'editform',
  CHAT_WINDOW            = 'chat-window',
  VERIFY_ID              = 'verify-id',
  HOROSCOPE              = 'horoscope',
  RECHARGE               = 'recharge',
  RENEWAL                = 'renewal',
  MY_MEMBERSHIP          = 'my-membership',
  PAYMENT                = 'payment',
  PAYMENT_SUCCESS        = 'payment-success',
  ADD_PHOTO_INTERMEDIATE = 'addphoto-intermediate',
  ADD_PHOTO_PUBLISH      = 'addphoto-publish',
  PHOTO_REJECTION        = 'photo-rejection',
}
