// Registration form field keys — used in form state and API payloads
export enum ERegistrationField {
  CREATED_BY = 'CREATEDBY',
  GENDER = 'GENDER',
  NAME = 'NAME',
  MARITAL_STATUS = 'MARITALSTATUS',
  YEAR = 'YEAR',
  MONTH = 'MONTH',
  DATE = 'DATE',
  AGE = 'AGE',
  HEIGHT = 'HEIGHT',
  STATE = 'STATE',
  CITY = 'CITY',
  QUALIFICATION = 'QUALIFICATION',
  OCCUPATION = 'OCCUPATION',
  MOBILE_NO = 'MOBILENO',
  RELIGION = 'RELIGION',
  CASTE = 'CASTE',
  SUBCASTE = 'SUBCASTE',
  HORO_STATE = 'HOROSTATE',
  HORO_CITY = 'HOROCITY',
  MOTHER_TONGUE = 'MOTHERTONGUE',
  INCOME = 'INCOME',
  NRI_STATE = 'NRISTATE',
  NRI_COUNTRY = 'NRICOUNTRY',
  NATIVE_CITY = 'NATIVECITY',
  NATIVE_STATE = 'NATIVESTATE',
  COUNTRY = 'COUNTRY',
  COUNTRY_CODE = 'COUNTRYCODE',
  MONTHLY_INCOME = 'MONTHLYINCOME',
  INCOME_TYPE = 'INCOMETYPE',
  HOME_STATE = 'HOMESTATE',
  HOME_CITY = 'HOMECITY',
  HEIGHT_CATEGORY = 'HEIGHTCATEGORY',
  DATE_OF_BIRTH = 'DATEOFBIRTH',
  EATING_HABITS = 'EATINGHABITS',
  ADD_PHOTO = 'ADDPHOTO',
  LOCATION = 'LOCATION',
  GOTHRA = 'GOTHRA',
  DIVISION = 'DIVISION',
  ADD_FAMILY_DETAILS = 'ADDFAMILYDETAILS',
  ADD_PROPERTY_DETAILS = 'ADDPROPERTYDETAILS',
  ASSETS = 'PROPERTY',
  GENERATE_HOROSCOPE = 'GENERATEHOROSCOPE',
  SELECT_BIRTH = 'SELECTBIRTH',
  SELECT_DOSHAM = 'SELECTDOSHAM',
  HAVE_DOSHAM = 'HAVE_DOSHAM',
  BROTHERS = 'BROTHERS',
  SISTERS = 'SISTERS',
  HOME_TOWN = 'HOMETOWN',
  PROPERTY = 'PROPERTY',
  STAR_RASSI = 'STARRASSI',
  RAASI = 'RAASI',
  STAR = 'STAR',
  DOSHAM = 'DOSHAM',
  ID_VERIFY = 'IDVERIFY',
  LANG = 'LANG',
}

// Array/dropdown data keys used during registration flow
export enum ERegistrationArray {
  CREATED_BY = 'PROFILECREATEDBY',
  GENDER = 'GENDER',
  NAME = 'NAME',
  MARITAL_STATUS = 'MARITALSTATUS',
  HEIGHT = 'HEIGHT',
  STATE = 'STATE',
  CITY = 'CITY',
  QUALIFICATION = 'QUALIFICATION',
  OCCUPATION = 'OCCUPATION',
  RELIGION = 'RELIGION',
  CASTE = 'CASTE',
  SUBCASTE = 'SUBCASTE',
  MOTHER_TONGUE = 'MOTHERTONGUE',
  INCOME = 'INCOME',
  NRI_STATE = 'NRISTATE',
  NRI_COUNTRY = 'NRICOUNTRY',
  HOME_STATE = 'HOMESTATE',
  HOME_CITY = 'HOMECITY',
  EATING_HABITS = 'EATINGHABITS',
  ALL_MOTHER_TONGUE = 'ALLMOTHERTONGUE',
  MOTHER_TONGUES = 'MOTHERTONGUES',
  STATE_OBJ = 'STATEOBJ',
  EDUCATION = 'EDUCATION',
  GOTHRAM = 'GOTHRAM',
  YEARS = 'YEARS',
  ASSETS = 'ASSETS',
  COUNTRY_LIST = 'COUNTRYLIST',
  DATE_OF_BIRTH = 'DATEOFBIRTH',
  HOME_TOWN = 'HOMETOWN',
  PROPERTY = 'PROPERTY',
  STAR_RASSI = 'STARRASSI',
  RAASI = 'RAASI',
  STAR = 'STAR',
  DOSHAM = 'DOSHAM',
  DOSHAM_HASH = 'DOSHAMHASH',
  NEW_HEIGHT = 'NEWHEIGHT',
  NEW_HEIGHT_MALE = 'NEWHEIGHTMALE',
  NEW_HEIGHT_FEMALE = 'NEWHEIGHTFEMALE',
}

// Maps registration step number → screen/module name for analytics and navigation
export const RegistrationStepMap: Record<number, string> = {
  1: 'profilecreatedby',
  2: 'name',
  3: 'gender',
  4: 'maritalstatus',
  5: 'dob-year',
  6: 'dob-age',
  7: 'height',
  9: 'loc',
  10: 'education',
  11: 'occupation',
  12: 'salary',
  13: 'religion',
  14: 'caste',
  16: 'gothra',
  18: 'verifymobno',
  19: 'congrats',
  20: 'addPhoto',
  21: 'property',
  22: 'addhoroscope',
  26: 'editmobileno',
  27: 'fewmoredetails',
  28: 'brothers',
  29: 'sisters',
  31: 'star',
  32: 'rasi',
  33: 'dosham',
  38: 'eatinghabits',
  39: 'mothertongue',
  43: 'heightcategory',
  44: 'hometown',
  46: 'hometownValue',
}

// AsyncStorage keys for persisting registration state across sessions
export enum ERegStorageKey {
  KEY_VALUES = 'REGISTRATIONKEYVALUES',
  VALUES = 'REGISTRATIONVALUES',
  ARRAYS = 'REGISTRATIONARRAYS',
}

// Analytics module names for registration steps
export enum ERegQueryModule {
  profilecreatedby = 'profilecreatedby',
  gender = 'gender',
  name = 'name',
  maritalstatus = 'maritalstatus',
  dobyear = 'dob-year',
  dobage = 'dob-age',
  height = 'height',
  loc = 'loc',
  education = 'education',
  occupation = 'occupation',
  salary = 'salary',
  religion = 'religion',
  caste = 'caste',
  gothra = 'gothra',
  verifymobno = 'verifymobno',
  congrats = 'congrats',
  addPhoto = 'addPhoto',
  editmobileno = 'editmobileno',
  fewmoredetails = 'fewmoredetails',
  property = 'property',
  brothers = 'brothers',
  sisters = 'sisters',
  star = 'star',
  raasi = 'raasi',
  dosham = 'dosham',
  addhoroscope = 'addhoroscope',
  eatinghabits = 'eatinghabits',
  mothertongue = 'mothertongue',
  heightcategory = 'heightcategory',
  country = 'country',
  state = 'state',
  city = 'city',
  subcaste = 'subcaste',
  registration = 'registration',
  partialregistration = 'partialregistration',
  autologin = 'autologin',
  logintruecall = 'logintruecall',
  managephoto = 'managephoto',
  deletephoto = 'deletephoto',
  updatefamily = 'updatefamily',
  editprofileupdate = 'editprofileupdate',
  nativeCountry = 'nativecountry',
  nativestate = 'nativestate',
  nativecity = 'nativecity',
  horostate = 'horostate',
  horocity = 'horocity',
  homestate = 'homestate',
  homecity = 'homecity',
  monthlyincome = 'monthlyincome',
  language = 'language',
  switchlanguage = 'switchlanguage',
}
