// Inbound deep-link resolver.
//
// Two kinds of inbound paths, both reachable via the prefixes below (this
// build's custom scheme + its flavor's HTTPS App Link domain — see
// app.config.js's per-flavor `scheme`/`intentFilters`/`associatedDomains`):
//
//  - Semantic paths (e.g. `viewprofile/:matriId`) — handled entirely by
//    React Navigation's own `linking.config.screens` (navigation/RootNavigation.tsx),
//    nothing here.
//  - Resolver path (`dl?page_id=<id>`) — for backend/campaign-generated links
//    and AppsFlyer OneLink resolution (wired in analyticsService.ts). Reuses
//    the already-verified page_id landing logic in pageLandingService.ts
//    instead of building a second routing table.
//
// Deliberately native-app only, not the web/PWA build — that build has its
// own separate, pre-existing handoff mechanism (webviewHandoffService.ts's
// `#/webview/:type/:param/:page_id/:token` hash-route parsing).
//
// Generate resolver links with buildResolverLink() below, not a hand-written
// `scheme://dl?...` string — expo-linking's createURL() produces the
// triple-slash form (`scheme:///dl?...`) this app's own `prefixes` expect; a
// double-slash `scheme://dl` URL parses "dl" as the URL *host*, not the
// path, and silently fails to match here.
//
// Auth timing: a link tapped while logged out (or mid cold-start, before the
// session-refresh call resolves) can't navigate yet — resetTo()/navigate()
// silently no-op until NavigationContainer is ready. In that case the
// page_id is stashed via capturePendingDeepLink() and consumed once by
// contexts/AuthContext.tsx's own post-auth landing calls (taking priority
// over the backend's own WEBVIEWURL-derived page_id for that one landing
// decision), rather than building a full pending-intent framework.
//
// A THIRD kind of inbound link also lands here: any path under this build's
// own API host (constants/env's EnvConfig.api, e.g. stgoapi.jodii.app) — the
// legacy backend-resolved link (e.g. registration/linksms/v1?PARM=...), a
// real link still generated by the live backend today. The old Android app
// doesn't special-case this path at all: for ANY tapped link whose host
// isn't jodii.onelink.me, it strips the scheme+host and GETs whatever path+
// query is left against its own configured API — regardless of the link's
// own host — then reads back {ID, MSGTYPE, COMMONDATA}. If ID matches the
// logged-in member it re-authenticates and lands via MSGTYPE (the SAME
// numbering scheme as FCM push notifications — see notificationService.ts's
// routePushNotificationTap, reused here); if ID doesn't match, it force-logs-
// out rather than adopting the new ID. It also only ever runs when already
// logged in — a logged-out tap is silently ignored, matching Android's own
// behavior (confirmed: no code path anywhere provisions a brand-new member
// from this link). handleApiHostLink() below replicates this exactly.

import * as Linking from 'expo-linking'
import Constants from 'expo-constants'
import FLAVORS from '../constants/flavorConfig'
import { EnvConfig } from '../constants/env'
import { getItem, setItem, removeItem } from './storageService'
import { StorageKeys as SK } from '../constants/storage.keys'
import { handlePageLanding } from './pageLandingService'
import { apiCall, clearSession } from './apiClient'
import { refreshSession } from './homeService'
import { routePushNotificationTap } from './notificationService'
import { disconnectSocket } from './socketService'
import { waitForNavigationReady } from '../utils/navigationRef'

export function getLinkingPrefixes(): string[] {
  const appFlavor = Constants.expoConfig?.extra?.appFlavor ?? 'jodii'
  const domain = (FLAVORS as Record<string, { domain: string }>)[appFlavor]?.domain ?? FLAVORS.jodii.domain
  const base = [`https://${domain}/jodii`]
  try { base.unshift(Linking.createURL('/')) } catch {}
  return base
}

// Strips whichever of this build's prefixes the URL starts with, returning
// the bare path (leading slash trimmed, query string removed) — or null if
// the URL doesn't match any of them (a foreign scheme/domain).
function stripToPath(url: string): string | null {
  const prefix = getLinkingPrefixes().find(p => url.startsWith(p))
  if (prefix === undefined) return null
  return url.slice(prefix.length).split('?')[0].replace(/^\/+/, '')
}

export function buildResolverLink(pageId: string): string {
  return Linking.createURL('dl', { queryParams: { page_id: pageId } })
}

export function parseResolverLink(url: string): { pageId: string } | null {
  if (stripToPath(url) !== 'dl') return null
  const { queryParams } = Linking.parse(url)
  const pageId = queryParams?.page_id
  return typeof pageId === 'string' && pageId ? { pageId } : null
}

const PENDING_KEY = SK.App.PENDING_DEEPLINK_PAGE_ID

export async function capturePendingDeepLink(pageId: string): Promise<void> {
  await setItem(PENDING_KEY, pageId)
}

export async function consumePendingDeepLinkPageId(): Promise<string | undefined> {
  const pageId = await getItem(PENDING_KEY)
  if (pageId) await removeItem(PENDING_KEY)
  return pageId ?? undefined
}

// Shared by both the URL-based resolver path below and AppsFlyer's
// onDeepLink callback (analyticsService.ts) — a page_id is a page_id
// regardless of which transport it arrived on.
export async function resolvePageId(pageId: string): Promise<void> {
  const userId = await getItem(SK.Auth.USER_ID)
  const ready = userId ? await waitForNavigationReady() : false
  if (userId && ready) {
    await handlePageLanding(pageId, userId)
  } else {
    await capturePendingDeepLink(pageId)
  }
}

function isApiHostLink(url: string): boolean {
  try {
    return url.startsWith(`${new URL(EnvConfig.api).origin}/`)
  } catch {
    return false
  }
}

// Legacy backend-resolved link (see header comment) — any path under this
// build's own API host. Always returns true once matched: this is never a
// React Navigation screen path, so it must never fall through to
// `config.screens` regardless of what happens inside.
async function handleApiHostLink(url: string): Promise<boolean> {
  if (!isApiHostLink(url)) return false

  try {
    const userId = await getItem(SK.Auth.USER_ID)
    if (!userId) return true // Android: not logged in → link silently ignored, same here

    const origin = new URL(EnvConfig.api).origin
    const relative = url.slice(origin.length + 1)
    const [path, query = ''] = relative.split('?')
    const result = await apiCall(`${EnvConfig.api}${path}`, 'GET', query)
    const { ID, MSGTYPE } = result?.RESPONSE ?? {}

    if (String(result?.ERRCODE) !== '0' || !ID) return true // no-op on error — matches Android's swallow-all try/catch

    if (String(ID) === userId) {
      // Re-validate/refresh tokens — Android's performAutoLogin(id, msgType).
      // COMMONDATA isn't forwarded: no screen in this port consumes it yet.
      await refreshSession()
      if (await waitForNavigationReady()) routePushNotificationTap({ messagetype: MSGTYPE })
    } else {
      // Android's logoutViewModel() — force logout, never adopt the new ID.
      disconnectSocket()
      await clearSession()
    }
  } catch {
    // swallow — matches Android's deepLink()/update() try/catch
  }
  return true
}

// Called from RootNavigation.tsx's `linking.getInitialURL`/`linking.subscribe`
// overrides, before React Navigation gets a chance to match the URL against
// `config.screens`. Returns true once the URL has been fully handled here
// (either resolver path above) — the caller should swallow it. Returns false
// for every other URL (semantic paths, or anything unrecognized), which the
// caller should pass straight through to React Navigation's normal handling.
export async function handleResolverURL(url: string): Promise<boolean> {
  const resolved = parseResolverLink(url)
  if (resolved) {
    await resolvePageId(resolved.pageId)
    return true
  }
  return handleApiHostLink(url)
}
