// Re-applies the custom Razorpay Custom Integration bridge (RazorpayBridgeModule/
// RazorpayWebView/RazorpayBridgePackage — see service/paymentService.ts
// initRazorpayNative()) on every prebuild. Without this plugin, `expo prebuild
// --clean` regenerates android/ from scratch and silently drops these files,
// the build.gradle dependency, the MainApplication package registration, and
// the AndroidManifest entries — breaking Android payments with no build error.
const {
  withDangerousMod, withAppBuildGradle, withMainApplication, withAndroidManifest,
} = require('@expo/config-plugins');
const { mergeContents } = require('@expo/config-plugins/build/utils/generateCode');
const fs = require('fs');
const path = require('path');

const PACKAGE_PATH = 'jodii/app';
const SRC_DIR = path.join(__dirname, 'android-native-src', 'razorpay');
const RAZORPAY_GRADLE_DEP = 'implementation "com.razorpay:customui:3.9.22"';
// Value removed for this push, matching the same blank value in
// android/app/src/main/AndroidManifest.xml (only used if that file gets
// regenerated by a clean prebuild instead of hand-edited directly) — re-add
// the real Razorpay Key ID before building again.
const DEFAULT_RAZORPAY_API_KEY = '';

function copyNativeSources(projectRoot) {
  const javaDir = path.join(projectRoot, 'android', 'app', 'src', 'main', 'java', PACKAGE_PATH);
  const layoutDir = path.join(projectRoot, 'android', 'app', 'src', 'main', 'res', 'layout');
  fs.mkdirSync(javaDir, { recursive: true });
  fs.mkdirSync(layoutDir, { recursive: true });

  for (const file of ['RazorpayBridgeModule.kt', 'RazorpayWebView.kt', 'RazorpayBridgePackage.kt']) {
    fs.copyFileSync(path.join(SRC_DIR, file), path.join(javaDir, file));
  }
  fs.copyFileSync(
    path.join(SRC_DIR, 'razorpay_web_view.xml'),
    path.join(layoutDir, 'razorpay_web_view.xml'),
  );
}

function withRazorpayGradleDependency(config) {
  return withAppBuildGradle(config, modConfig => {
    if (!modConfig.modResults.contents.includes(RAZORPAY_GRADLE_DEP)) {
      modConfig.modResults.contents = modConfig.modResults.contents.replace(
        /dependencies\s*\{/,
        `dependencies {\n    ${RAZORPAY_GRADLE_DEP}`,
      );
    }
    return modConfig;
  });
}

function withRazorpayPackageRegistration(config) {
  return withMainApplication(config, modConfig => {
    const { contents, didMerge } = mergeContents({
      src: modConfig.modResults.contents,
      newSrc: '          add(RazorpayBridgePackage())',
      tag: 'razorpay-bridge-package',
      anchor: /packages\.apply\s*\{/,
      offset: 1,
      comment: '//',
    });
    if (didMerge) modConfig.modResults.contents = contents;
    return modConfig;
  });
}

function withRazorpayManifestEntries(config, { razorpayApiKey }) {
  return withAndroidManifest(config, modConfig => {
    const application = modConfig.modResults.manifest.application?.[0];
    if (!application) return modConfig;

    // Not using AndroidConfig.Manifest.addMetaDataItemToMainApplication() here —
    // against this project's manifest it serializes the meta-data tag as a
    // sibling of <manifest> instead of a child of <application> (reproduced
    // in isolation against a fresh prebuild output). Direct array manipulation,
    // same as the activity entry below, avoids that bug.
    const metaData = application['meta-data'] ?? (application['meta-data'] = []);
    if (!metaData.some(m => m.$?.['android:name'] === 'com.razorpay.ApiKey')) {
      metaData.push({ $: { 'android:name': 'com.razorpay.ApiKey', 'android:value': razorpayApiKey } });
    }

    const activities = application.activity ?? (application.activity = []);
    const alreadyPresent = activities.some(a => a.$?.['android:name'] === '.RazorpayWebView');
    if (!alreadyPresent) {
      activities.push({
        $: {
          'android:name': '.RazorpayWebView',
          'android:exported': 'false',
          'android:theme': '@style/Theme.AppCompat.Light.NoActionBar',
        },
      });
    }

    return modConfig;
  });
}

module.exports = function withRazorpayAndroidBridge(config, { razorpayApiKey = DEFAULT_RAZORPAY_API_KEY } = {}) {
  config = withDangerousMod(config, [
    'android',
    modConfig => {
      copyNativeSources(modConfig.modRequest.projectRoot);
      return modConfig;
    },
  ]);

  config = withRazorpayGradleDependency(config);
  config = withRazorpayPackageRegistration(config);
  config = withRazorpayManifestEntries(config, { razorpayApiKey });

  return config;
};
